name: Build Windows App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Pub get
        run: flutter pub get

      # 🔹 Génère l'icône Windows depuis assets/icon.png
      - name: Generate launcher icons (Windows)
        run: dart run flutter_launcher_icons

      # (optionnel) Vérifie que l'icône a bien été générée
      - name: Verify Windows icon generated
        shell: pwsh
        run: |
          if (-not (Test-Path "windows/runner/resources/app_icon.ico")) {
            Write-Error "app_icon.ico not found. Check flutter_launcher_icons config and assets/icon.png"
          }

      - name: Build Windows (Release)
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: launcher_url-windows
          path: build/windows/x64/runner/Release/